### ISSUE TITLE
Bad wordcount example

### ISSUE THREAD

**Issue by k0pernicus** [exercism/nim#48]
I am stucked at `wordcount`, so I downloaded this repository to run the example, and try to run the test with `nim c -r word_count_test.nim`.

An error occured: `word_count_test.nim(3, 8) Error: cannot open 'wordcount'`, because the code is in `example.nim`.

If I change `example.nim` to `wordcount.nim`, and I run the tests again, 4 tests failed...
```
Hint: /Users/antonin/exercism/nim/nim/exercises/word-count/word_count_test  [Exec]
[OK] count one word
[OK] count one of each
[OK] count multiple occurrences
word_count_test.nim(41,15): Check failed: result == expected
result was {: 12, as: 1, car: 1, carpet: 1, java: 1, javascript: 1}
expected was {as: 1, car: 1, carpet: 1, java: 1, javascript: 1}
[FAILED] ignore punctuation
word_count_test.nim(47,15): Check failed: result == expected
result was {: 2, 1: 1, 2: 1, testing: 2}
expected was {1: 1, 2: 1, testing: 2}
[FAILED] include numbers
[OK] normalize case
word_count_test.nim(59,15): Check failed: result == expected
result was {: 6, 1: 1, 2: 1, testing: 2}
expected was {1: 1, 2: 1, testing: 2}
[FAILED] prefix punctuation
word_count_test.nim(66,15): Check failed: result == expected
result was {: 1, broken: 1, hey: 1, is: 1, my: 1, spacebar: 1}
expected was {broken: 1, hey: 1, is: 1, my: 1, spacebar: 1}
[FAILED] symbols are separators
Error: execution of an external program failed: '/Users/antonin/exercism/nim/nim/exercises/word-count/word_count_test '
```

**Comment by amscotti** [comment]
Hi @k0pernicus,
The code being in `example.nim` is how the test software works, if you clone the project you will see code under `_test` called `check_exercises.nim`. If you build and run this file, it will execute all the test in this track. One of the steps it does is rename the `example.nim`.

Based on your PR #49, I think you found that your issue was due to having a new version of Nim on your system then what our CI system was running. Right now this should all be fix.

I'm going to close this issue but please let me know if I missed something and this is still an issue. Thanks for pointing this issue out.
